# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b218a93e315bda60a8301bd543346e20de415fb3bccf9f7153a17ec03b74bf03fab26eb4010fb6bd3ec5316a4cea7a175eab53af2e592bfd97234aaeb11ea7bb

test:
  secret_key_base: 37c2b2a01009ded6756f424fb0092c56888b0f8adcbf60dbb7c09c8b0a4f3c5d5b07a24b5fec187b3bf800ab6fb59106322303dbd36ff4f1a8453f3c01e131f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
