# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(email: "admin@ok.com", name: "Admin", password: "okokok")
User.create!(email: "maggie@ok.com", name: "Maggie", password: "okokok")
User.create!(email: "chris@ok.com", name: "Chris", password: "okokok")
User.create!(email: "jacob@ok.com", name: "Jacob", password: "okokok")
User.create!(email: "mike@ok.com", name: "Mike", password: "okokok")
User.create!(email: "kenny@ok.com", name: "Kenny", password: "okokok")
User.create!(email: "norris", name: "Norris", password: "norris")
User.create!(email: "barnlfarnl@ok.com", name: "Barnlfarnl", password: "okokok")
User.create!(email: "glorfindel@ok.com", name: "Glorfindel", password: "okokok")
User.create!(email: "darwin@ok.com", name: "Darwin", password: "okokok")
User.create!(email: "louise@ok.com", name: "Louise", password: "okokok")
User.create!(email: "eleanor@ok.com", name: "Eleanor", password: "okokok")
User.create!(email: "fay@ok.com", name: "Fay", password: "okokok")
User.create!(email: "marzipan@ok.com", name: "Marzipan", password: "okokok")
User.create!(email: "spotty@ok.com", name: "Spotty", password: "okokok")
User.create!(email: "colin@ok.com", name: "Colin", password: "okokok")
User.create!(email: "jeremy@ok.com", name: "Jeremy", password: "okokok")
User.create!(email: "john@ok.com", name: "John", password: "okokok")
User.create!(email: "david@ok.com", name: "David", password: "okokok")
User.create!(email: "matt@ok.com", name: "Matt", password: "okokok")
User.create!(email: "charles@ok.com", name: "Charles", password: "okokok")
User.create!(email: "tshirt@ok.com", name: "Tshirt", password: "okokok")
User.create!(email: "florin@ok.com", name: "Florin", password: "okokok")
User.create!(email: "zak@ok.com", name: "Zak", password: "okokok")
User.create!(email: "dennis@ok.com", name: "Dennis", password: "okokok")
User.create!(email: "constance@ok.com", name: "Constance", password: "okokok")
User.create!(email: "jessie@ok.com", name: "Jessie", password: "okokok")
User.create!(email: "sam@ok.com", name: "Sam", password: "okokok")

User.find_by_email("admin@ok.com").profile.update!(location: "NYC", about: "I like giraffes!", age: 23, gender: "female")
User.find_by_email("maggie@ok.com").profile.update!(location: "NYC", about: "I'm awesome. I like fine art and Donna Summer. Florin is my buddy. I don't have any more fun. I code for fun except I get angsty and grumps.", age: 18, gender: "male")
User.find_by_email("chris@ok.com").profile.update!(location: "NYC", about: "I've forgotten how to think. It's been so long. So long.", age: 26, gender: "male")
User.find_by_email("jacob@ok.com").profile.update!(location: "NYC", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("mike@ok.com").profile.update!(location: "Thailand", about: "I like giraffes!", age: 23, gender: "female")
User.find_by_email("chris@ok.com").profile.update!(location: "Thailand", about: "I'm awesome. I like fine art and Donna Summer. Florin is my buddy. I don't have any more fun. I code for fun except I get angsty and grumps.", age: 18, gender: "male")
User.find_by_email("kenny@ok.com").profile.update!(location: "Thailand", about: "I've forgotten how to think. It's been so long. So long.", age: 26, gender: "male")
User.find_by_email("norris").profile.update!(location: "Thailand", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("barnlfarnl@ok.com").profile.update!(location: "Thailand", about: "I like giraffes!", age: 23, gender: "female")
User.find_by_email("glorfindel@ok.com").profile.update!(location: "Thailand", about: "I'm awesome. I like fine art and Donna Summer. Florin is my buddy. I don't have any more fun. I code for fun except I get angsty and grumps.", age: 18, gender: "male")
User.find_by_email("darwin@ok.com").profile.update!(location: "Massat", about: "I've forgotten how to think. It's been so long. So long.", age: 26, gender: "male")
User.find_by_email("louise@ok.com").profile.update!(location: "Massat", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("eleanor@ok.com").profile.update!(location: "Massat", about: "I like giraffes!", age: 23, gender: "female")
User.find_by_email("fay@ok.com").profile.update!(location: "Massat", about: "I'm awesome. I like fine art and Donna Summer. Florin is my buddy. I don't have any more fun. I code for fun except I get angsty and grumps.", age: 18, gender: "male")
User.find_by_email("marzipan@ok.com").profile.update!(location: "Massat", about: "I've forgotten how to think. It's been so long. So long.", age: 26, gender: "male")
User.find_by_email("spotty@ok.com").profile.update!(location: "Massat", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("jeremy@ok.com").profile.update!(location: "Rolla", about: "I like giraffes!", age: 23, gender: "female")
User.find_by_email("john@ok.com").profile.update!(location: "Rolla", about: "I'm awesome. I like fine art and Donna Summer. Florin is my buddy. I don't have any more fun. I code for fun except I get angsty and grumps.", age: 18, gender: "male")
User.find_by_email("david@ok.com").profile.update!(location: "Rolla", about: "I've forgotten how to think. It's been so long. So long.", age: 26, gender: "male")
User.find_by_email("matt@ok.com").profile.update!(location: "Rolla", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("charles@ok.com").profile.update!(location: "Rolla", about: "I like giraffes!", age: 23, gender: "female")
User.find_by_email("tshirt@ok.com").profile.update!(location: "Rolla", about: "I'm awesome. I like fine art and Donna Summer. Florin is my buddy. I don't have any more fun. I code for fun except I get angsty and grumps.", age: 18, gender: "male")
User.find_by_email("florin@ok.com").profile.update!(location: "Kansas City", about: "I've forgotten how to think. It's been so long. So long.", age: 26, gender: "male")
User.find_by_email("zak@ok.com").profile.update!(location: "Kansas City", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("dennis@ok.com").profile.update!(location: "Kansas City", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("constance@ok.com").profile.update!(location: "Kansas City", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("jessie@ok.com").profile.update!(location: "Kansas City", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")
User.find_by_email("sam@ok.com").profile.update!(location: "Kansas City", about: "Ohhhhh my god. Stream of obscenities.", age: 26, gender: "male")

User.find_by_email("sam@ok.com").events.create!(location: "NYC", title: "Work at MLB!", date: Date.today, time: "5:00", description: "I miss you all!")
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 1, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 11, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 5, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 6, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 8, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 18, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 21, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 10, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 12, event_id: 1, invitation: true)
User.find_by_email("sam@ok.com").sent_requests.create!(receiver_id: 3, event_id: 1, invitation: true)
