# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: "admin@ok.com", name: "Admin", password: "okokok")
User.create(email: "maggie@ok.com", name: "Maggie", password: "okokok")
User.create(email: "chris@ok.com", name: "Chris", password: "okokok")
User.create(email: "jacob@ok.com", name: "Jacob", password: "okokok")
User.create(email: "mike@ok.com", name: "Mike", password: "okokok")
User.create(email: "kenny@ok.com", name: "Kenny", password: "okokok")
User.create(email: "norris", name: "Norris", password: "norris")
User.create(email: "barnlfarnl@ok.com", name: "Barnlfarnl", password: "okokok")
User.create(email: "glorfindel@ok.com", name: "Glorfindel", password: "okokok")
User.create(email: "darwin@ok.com", name: "Darwin", password: "okokok")
User.create(email: "louise@ok.com", name: "Louise", password: "okokok")
User.create(email: "eleanor@ok.com", name: "Eleanor", password: "okokok")
User.create(email: "fay@ok.com", name: "Fay", password: "okokok")
User.create(email: "marzipan@ok.com", name: "Marzipan", password: "okokok")
User.create(email: "spotty@ok.com", name: "Spotty", password: "okokok")
User.create(email: "colin@ok.com", name: "Colin", password: "okokok")
User.create(email: "jeremy@ok.com", name: "Jeremy", password: "okokok")
User.create(email: "john@ok.com", name: "John", password: "okokok")
User.create(email: "david@ok.com", name: "David", password: "okokok")
User.create(email: "matt@ok.com", name: "Matt", password: "okokok")
User.create(email: "charles@ok.com", name: "Charles", password: "okokok")
User.create(email: "tshirt@ok.com", name: "Tshirt", password: "okokok")
User.create(email: "florin@ok.com", name: "Florin", password: "okokok")
User.create(email: "zak@ok.com", name: "Zak", password: "okokok")
User.create(email: "dennis@ok.com", name: "Dennis", password: "okokok")
User.create(email: "constance@ok.com", name: "Constance", password: "okokok")
User.create(email: "jessie@ok.com", name: "Jessie", password: "okokok")
User.create(email: "sam@ok.com", name: "Sam", password: "okokok")
